In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
 # Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
from sklearn.linear_model import Ridge  # Import Ridge for Linear Regression with Regularization
from sklearn.model_selection import GridSearchCV

# Define the parameter grid for Ridge Regression
param_grid = {
    'alpha': [0.1, 1.0, 10.0, 100.0],  # Regularization strength
    'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']  # Different solvers
}

In [11]:
# Initialize GridSearchCV with Ridge Regression
grid = GridSearchCV(Ridge(), param_grid, refit=True, verbose=3, n_jobs=-1, cv=5)

# Fitting the model for grid search on the training data
grid.fit(X_train, y_train)

Fitting 5 folds for each of 28 candidates, totalling 140 fits

GridSearchCV(cv=5, estimator=Ridge(), n_jobs=-1,
             param_grid={'alpha': [0.1, 1.0, 10.0, 100.0],
                         'solver': ['auto', 'svd', 'cholesky', 'lsqr',
                                    'sparse_cg', 'sag', 'saga']},
             verbose=3)

In [14]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'alpha': 10.0, 'solver': 'sag'}: 0.7855293356382267

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.037797,0.027631,0.000000,0.000000,0.1,auto,"{'alpha': 0.1, 'solver': 'auto'}",0.707281,0.690693,0.757148,0.710842,0.714428,0.716078,0.022085,18
1,0.015513,0.013504,0.000000,0.000000,0.1,svd,"{'alpha': 0.1, 'solver': 'svd'}",0.707281,0.690693,0.757148,0.710842,0.714428,0.716078,0.022085,18
2,0.002361,0.001983,0.000957,0.001915,0.1,cholesky,"{'alpha': 0.1, 'solver': 'cholesky'}",0.707281,0.690693,0.757148,0.710842,0.714428,0.716078,0.022085,18
3,0.000000,0.000000,0.000000,0.000000,0.1,lsqr,"{'alpha': 0.1, 'solver': 'lsqr'}",0.707282,0.690692,0.757147,0.710847,0.714428,0.716079,0.022084,16
4,0.006334,0.004099,0.000000,0.000000,0.1,sparse_cg,"{'alpha': 0.1, 'solver': 'sparse_cg'}",0.707282,0.690692,0.757147,0.710847,0.714428,0.716079,0.022084,17
5,0.001002,0.002003,0.000000,0.000000,0.1,sag,"{'alpha': 0.1, 'solver': 'sag'}",0.707277,0.690595,0.757139,0.710843,0.714434,0.716058,0.022104,21
6,0.006260,0.007667,0.000000,0.000000,0.1,saga,"{'alpha': 0.1, 'solver': 'saga'}",0.707281,0.690692,0.757153,0.710845,0.714428,0.716080,0.022087,15
7,0.000000,0.000000,0.000000,0.000000,1.0,auto,"{'alpha': 1.0, 'solver': 'auto'}",0.707396,0.690706,0.757029,0.711055,0.714294,0.716096,0.022020,12
8,0.000000,0.000000,0.003128,0.006256,1.0,svd,"{'alpha': 1.0, 'solver': 'svd'}",0.707396,0.690706,0.757029,0.711055,0.714294,0.716096,0.022020,12
9,0.001119,0.002237,0.000176,0.000353,1.0,cholesky,"{'alpha': 1.0, 'solver': 'cholesky'}",0.707396,0.690706,0.757029,0.711055,0.714294,0.716096,0.022020,12
10,0.001437,0.002875,0.000000,0.000000,1.0,lsqr,"{'alpha': 1.0, 'solver': 'lsqr'}",0.707397,0.690705,0.757028,0.711060,0.714294,0.716097,0.022020,9
11,0.001703,0.003405,0.001703,0.003405,1.0,sparse_cg,"{'alpha': 1.0, 'solver': 'sparse_cg'}",0.707397,0.690705,0.757028,0.711060,0.714294,0.716097,0.022020,10
12,0.004614,0.003794,0.001312,0.002625,1.0,sag,"{'alpha': 1.0, 'solver': 'sag'}",0.707387,0.690712,0.757030,0.711062,0.714289,0.716096,0.022020,11
13,0.001737,0.003473,0.000000,0.000000,1.0,saga,"{'alpha': 1.0, 'solver': 'saga'}",0.707394,0.690716,0.757030,0.711053,0.714294,0.716097,0.022019,8
14,0.003473,0.004254,0.000000,0.000000,10.0,auto,"{'alpha': 10.0, 'solver': 'auto'}",0.708399,0.690705,0.755727,0.712999,0.712845,0.716135,0.021423,4
15,0.000000,0.000000,0.000000,0.000000,10.0,svd,"{'alpha': 10.0, 'solver': 'svd'}",0.708399,0.690705,0.755727,0.712999,0.712845,0.716135,0.021423,4
16,0.000000,0.000000,0.001702,0.003404,10.0,cholesky,"{'alpha': 10.0, 'solver': 'cholesky'}",0.708399,0.690705,0.755727,0.712999,0.712845,0.716135,0.021423,4
17,0.000656,0.000803,0.003091,0.003786,10.0,lsqr,"{'alpha': 10.0, 'solver': 'lsqr'}",0.708400,0.690704,0.755726,0.713004,0.712845,0.716136,0.021423,2
18,0.001895,0.001756,0.000000,0.000000,10.0,sparse_cg,"{'alpha': 10.0, 'solver': 'sparse_cg'}",0.708400,0.690704,0.755726,0.713004,0.712845,0.716136,0.021423,3
19,0.003176,0.004649,0.000000,0.000000,10.0,sag,"{'alpha': 10.0, 'solver': 'sag'}",0.708412,0.690711,0.755732,0.713018,0.712842,0.716143,0.021422,1
20,0.002957,0.004124,0.000168,0.000336,10.0,saga,"{'alpha': 10.0, 'solver': 'saga'}",0.708403,0.690694,0.755721,0.712996,0.712843,0.716132,0.021423,7
21,0.000000,0.000000,0.002103,0.004205,100.0,auto,"{'alpha': 100.0, 'solver': 'auto'}",0.706683,0.681053,0.734424,0.717830,0.690618,0.706122,0.019012,25
22,0.003002,0.004409,0.000122,0.000245,100.0,svd,"{'alpha': 100.0, 'solver': 'svd'}",0.706683,0.681053,0.734424,0.717830,0.690618,0.706122,0.019012,24
23,0.000362,0.000724,0.000000,0.000000,100.0,cholesky,"{'alpha': 100.0, 'solver': 'cholesky'}",0.706683,0.681053,0.734424,0.717830,0.690618,0.706122,0.019012,25
24,0.000972,0.001190,0.000000,0.000000,100.0,lsqr,"{'alpha': 100.0, 'solver': 'lsqr'}",0.706683,0.681053,0.734414,0.717832,0.690618,0.706120,0.019009,27
25,0.000580,0.001160,0.003435,0.004232,100.0,sparse_cg,"{'alpha': 100.0, 'solver': 'sparse_cg'}",0.706683,0.681053,0.734414,0.717832,0.690618,0.706120,0.019009,27
26,0.002857,0.003813,0.001907,0.003815,100.0,sag,"{'alpha': 100.0, 'solver': 'sag'}",0.706681,0.681061,0.734428,0.717833,0.690617,0.706124,0.019011,23
27,0.002320,0.003174,0.000000,0.000000,100.0,saga,"{'alpha': 100.0, 'solver': 'saga'}",0.706690,0.681058,0.734423,0.717844,0.690623,0.706128,0.019011,22

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 27
BMI: 12
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[143830.36848215]