In [2]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
 # Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestRegressor

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {
    'criterion': ['squared_error', 'absolute_error'],
    'max_features': ['auto', 'sqrt', 'log2'],
    'n_estimators': [10, 100]
}

# Initialize GridSearchCV with RandomForestRegressor
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)

# Fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [12]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8744418313579326

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.056542,0.005748,0.000650,0.000797,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",0.803737,0.720481,0.831056,0.795612,0.765641,0.783305,0.037704,8
1,0.479889,0.017790,0.022821,0.006203,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.799364,0.750687,0.830666,0.810135,0.765540,0.791278,0.029266,5
2,0.045247,0.003994,0.000663,0.001325,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.786622,0.726515,0.812961,0.806413,0.735868,0.773676,0.035878,11
3,0.358309,0.028465,0.014264,0.009038,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.810526,0.766901,0.835212,0.833771,0.759024,0.801087,0.032434,3
4,0.040826,0.005032,0.005680,0.003140,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.787828,0.736482,0.806147,0.799999,0.724309,0.770953,0.033856,12
5,0.368146,0.017755,0.015238,0.005560,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.811437,0.768293,0.836459,0.833444,0.760482,0.802023,0.032016,1
6,0.177846,0.007678,0.002792,0.002594,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",0.765387,0.751552,0.799295,0.810604,0.749285,0.775225,0.025144,9
7,1.685854,0.047895,0.013028,0.002836,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.783309,0.767699,0.818009,0.809030,0.756484,0.786906,0.023513,6
8,0.099893,0.007466,0.005696,0.005465,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.784304,0.708105,0.847817,0.800708,0.733182,0.774823,0.049545,10
9,0.984105,0.029869,0.011516,0.005818,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.801403,0.770400,0.837877,0.826601,0.759946,0.799245,0.030404,4
10,0.103629,0.004766,0.001770,0.003541,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.807940,0.732132,0.819776,0.816232,0.746126,0.784441,0.037458,7
11,0.866188,0.029954,0.009773,0.007988,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.807739,0.771145,0.838588,0.825615,0.763952,0.801408,0.029418,2

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 27
BMI: 12
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#␣change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[46551.1388229]